### ISSUE TITLE
Thanks, and updates?

### ISSUE THREAD

**Issue by PVTejas** [jimmymasaru/focalboard-docker-arm#2]
First of all, I am so grateful that this exists. Being able to install a relatively recent version of focalboard on my raspi - I'm so glad I've got it up and running.

Since focalboard has stopped receiving updates, I wonder if you can update the image to the latest version? No worries if not, I'm still really glad to have this exist.

**Comment by jimmymasaru** [comment]
An updated image for version `7.8.9` has been pushed to Docker Hub. Unfortunately the build script fails for the latest `8.0.0` and I'm not planning on fixing it at the moment.

**Comment by PVTejas** [comment]
Completely understandable. Again, thanks for this project's existence.
